DATASETS = {
    "adult": {
        "loader": "UCI ML Repository",
        "description": "Census income classification dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "Barry Becker and Ronny Kohavi",
        "url": "https://archive.ics.uci.edu/dataset/2/adult",
        "license": "Creative Commons Attribution 4.0 International",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "auto_mpg": {
        "loader": "Seaborn",
        "description": "Vehicle fuel economy dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "R. Quinlan",
        "url": "https://archive.ics.uci.edu/ml/datasets/auto+mpg",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "bank_marketing": {
        "loader": "UCI ML Repository",
        "description": "Bank marketing campaign dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "Sérgio Moro, Paulo Rita, and Paulo Cortez",
        "url": "https://archive.ics.uci.edu/ml/datasets/bank+marketing",
        "license": "Creative Commons Attribution 4.0 International",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "bike_sharing": {
        "loader": "UCI ML Repository",
        "description": "Seoul bike-sharing demand dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "Seoul Open Data Plaza",
        "url": "https://archive.ics.uci.edu/dataset/560/seoul+bike+sharing+demand",
        "license": "Creative Commons Attribution 4.0 International",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "churn": {
        "loader": "Kaggle",
        "description": "Credit card churn dataset.",
        "source": "Kaggle",
        "creators": "Sakshi Goyal (Kaggle contributor)",
        "url": "https://www.kaggle.com/datasets/sakshigoyal7/credit-card-customers",
        "license": "CC0: Public Domain",
        "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    "cpu": {
        "loader": "Web-scraped data",
        "description": "Dataset of CPU pricing and performance characteristics.",
        "source": "datadepot",
        "creators": "Jeroen van Raak (data compilation)",
        "url": "https://github.com/vanraak/datadepot",
        "license": "CC BY 4.0",
        "license_url": "http://creativecommons.org/licenses/by/4.0/",
    },
    "credit_card_fraud": {
        "loader": "Kaggle",
        "description": "Anonymized credit card transactions labeled as fraudulent or legitimate.",
        "source": "Kaggle",
        "creators": "ULB Machine Learning Group and Worldline",
        "url": "https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud",
        "license": "Database Contents License (DbCL) v1.0",
        "license_url": "http://opendatacommons.org/licenses/dbcl/1.0/",
    },
    "credit_default": {
        "loader": "UCI ML Repository",
        "description": "Credit card default dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "I-Cheng Yeh",
        "url": "https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients",
        "license": "Creative Commons Attribution 4.0 International",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "diamonds": {
        "loader": "Seaborn",
        "description": "Diamond prices and characteristics dataset.",
        "source": "ggplot2 package",
        "creators": "Loose Diamonds Search Engine",
        "url": "https://ggplot2.tidyverse.org/reference/diamonds.html",
        "license": "MIT",
        "license_url": "https://ggplot2.tidyverse.org/LICENSE.html",
        "citation": "Wickham H (2016). ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York. ISBN 978-3-319-24277-4",
    },
    "fashion_mnist": {
        "loader": "TensorFlow/Keras",
        "description": "Fashion image classification dataset.",
        "source": "Zalando Research",
        "creators": "Zalando Research",
        "url": "https://keras.io/api/datasets/fashion_mnist/",
        "license": "MIT",
        "license_url": "https://opensource.org/license/mit/",
    },
    "hotel_booking": {
        "loader": "Kaggle",
        "description": "City hotel booking demand dataset, including completed and cancelled reservations.",
        "source": "Hotel Booking Demand Datasets",
        "creators": "Nuno Antonio, Ana de Almeida, and Luis Nunes",
        "url": "https://doi.org/10.1016/j.dib.2018.11.126",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "imdb": {
        "loader": "Hugging Face",
        "description": "Sentiment-classification dataset containing 50,000 IMDb movie reviews.",
        "source": "Stanford Large Movie Review Dataset (aclImdb)",
        "creators": "Andrew L. Maas, Raymond E. Daly, Peter T. Pham, Dan Huang, Andrew Y. Ng, and Christopher Potts",
        "url": "https://ai.stanford.edu/~amaas/data/sentiment/",
        "license": "Other",
        "license_url": "",
    },
    "laptop": {
        "loader": "Web-scraped data",
        "description": "Dataset of laptop specifications and prices.",
        "source": "datadepot",
        "creators": "Jeroen van Raak (data compilation)",
        "url": "https://github.com/vanraak/datadepot",
        "license": "CC BY 4.0",
        "license_url": "http://creativecommons.org/licenses/by/4.0/",
    },
    "loan_approval": {
        "loader": "Kaggle",
        "description": "Loan approval dataset with applicant financial information.",
        "source": "Kaggle",
        "creators": "Archit Sharma (Kaggle contributor)",
        "url": "https://www.kaggle.com/datasets/architsharma01/loan-approval-prediction-dataset",
        "license": "MIT",
        "license_url": "https://www.mit.edu/~amini/LICENSE.md",
    },
    "mnist": {
        "loader": "TensorFlow/Keras",
        "description": "Handwritten digit classification dataset.",
        "source": "MNIST database",
        "creators": "Y. LeCun, C. Cortes, and C. J. C. Burges",
        "url": "https://keras.io/api/datasets/mnist/",
        "license": "Creative Commons Attribution-Share Alike 3.0",
        "license_url": "https://creativecommons.org/licenses/by-sa/3.0/",
    },
    "nyc_taxi": {
        "loader": "datadepot",
        "description": "NYC yellow taxi zones dataset.",
        "source": "NYC TLC Trip Record Data",
        "creators": "NYC Taxi and Limousine Commission (TLC)",
        "url": "https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page",
        "license": "NYC.gov Terms of Use",
        "license_url": "https://www.nyc.gov/main/terms-of-use",
    },
    "online_shoppers": {
        "loader": "UCI ML Repository",
        "description": "Online shopping purchase-intention dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "C. Okan Sakar and Yomi Kastro",
        "url": "https://archive.ics.uci.edu/dataset/468/online+shoppers+purchasing+intention+dataset",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "real_estate": {
        "loader": "UCI ML Repository",
        "description": "Real estate valuation dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "I-Cheng Yeh",
        "url": "https://archive.ics.uci.edu/dataset/477/real+estate+valuation+data+set",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
    "wine_quality": {
        "loader": "UCI ML Repository",
        "description": "Red wine quality dataset.",
        "source": "UC Irvine Machine Learning Repository",
        "creators": "Paulo Cortez, António Cerdeira, Fernando Almeida, Telmo Matos, and José Reis",
        "url": "https://archive.ics.uci.edu/ml/datasets/wine+quality",
        "license": "CC BY 4.0",
        "license_url": "https://creativecommons.org/licenses/by/4.0/",
    },
}
